import type { Metadata } from "next";
import Footer from "@/components/Footer"; 
import "./globals.css";
import { poppins } from '@/app/ui/fonts';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const globalBodyStyling = `${poppins.className} antialiased`;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={globalBodyStyling}>
        {children}
        <Footer />
      </body>
    </html>
  );
}
