import "./globals.css";
import type { Metadata } from "next";
import { inter } from "./ui/fonts";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer"; 


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
